### ISSUE TITLE
[transport] Dialer and Listener should have more interface details

### ISSUE THREAD

**Issue by daviddias** [libp2p/js-interfaces#33]
Take inspiration from:
- https://nodejs.org/api/net.html#net_class_net_server
- https://nodejs.org/api/net.html#net_class_net_socket

And find the common denominators between transports/connections.

One of the most important parts is error handling

**Comment by jacobheun** [comment]
Closing this as stale, the transport documentation has improved significantly since this was created, https://github.com/libp2p/js-interfaces/tree/master/src/transport.
