### ISSUE TITLE
[crypto] Error for when invalid crypto data was recieved

### ISSUE THREAD

**Issue by mkg20001** [libp2p/js-interfaces#8]
Currently there's `InvalidCryptoExchangeError` which explicitly refers to a crypto exchange.

There should be something similar for errors that happen after the exchange while decoding the data, etc

Does anyone have a good name for it?

**Comment by jacobheun** [comment]
`DecodingError`?

**Comment by mkg20001** [comment]
Isn't that a bit specific just for decoding? Then we'd need a decryption error as well.

`InvalidCryptoTransmissionError` ?

Would fit with `InvalidCryptoExchangeError`

**Comment by jacobheun** [comment]
Yeah, that sounds appropriate.
